CREATE TABLE IF NOT EXISTS "LeavePolicy" (
  "id" TEXT NOT NULL DEFAULT 'default',
  "year" INTEGER NOT NULL,
  "casualDays" INTEGER NOT NULL DEFAULT 14,
  "sickDays" INTEGER NOT NULL DEFAULT 14,
  "unpaidDays" INTEGER NOT NULL DEFAULT 36,
  "earnedDays" INTEGER NOT NULL DEFAULT 18,
  "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "LeavePolicy_pkey" PRIMARY KEY ("id")
);
